name: bullets
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - importlib_metadata
  - jinja2
  - jupyter
  - python-dateutil
  - tqdm
  # maildown deps
  - boto3
  - cleo
  - mypy
  - typed-ast=1.3
  - pip:
    # for packaging and testing
    - s3pypi
    - safety
    # For running
    - ghapi
    - maildown
