name: bullets
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - jinja2
  - jupyter
  - python-dateutil
  - tqdm
  - pip:
    # for packaging and testing
    - s3pypi
    # For running
    - ghapi
